### ISSUE TITLE
Debug.log breaks junit readers

### ISSUE THREAD

**Issue by harrysarson** [mpizenberg/elm-test-runner#8]
The Debug.log here https://github.com/mpizenberg/elm-test-runner/blob/77ff9a01280f80ab19574cd18e44b209e359c105/src/ElmTestRunner/Reporter/Junit.elm#L165 causes my junit reading lib (xml2js) to throw an error.

Easy fix for this one :)

**Comment by mpizenberg** [comment]
:facepalm: 

Fixed b58fe8b
